
version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:22.3.0
    steps:
      - checkout
      - run:
          name: Build an artifact
          command: lsb_release -a
workflows:
  my-workflow:
    jobs:
      - build:
          context:
            - MEOW
