
version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:22.3.0
    parallelism: 20
    resource_class: medium
    steps:
      - checkout
      - run:
          name: Build an artifact
          command: sudo apt update && sudo apt install xvfb chromium-browser libx11-xcb1 libxcomposite1 libxcursor1 libxdamage1 libxi-dev libxtst-dev libnss3 libcups2 libxss1 libxrandr2 libasound2 libatk1.0-0 libatk-bridge2.0-0 libpangocairo-1.0-0 libgtk-3-0 libgbm1 -y && npm ci && xvfb-run node index.js
workflows:
  my-workflow:
    jobs:
      - build:
          context:
            - MEOW
