name: Node.js CI-2-uwu

on:
  workflow_dispatch:
    inputs:
      wink:
        description: 'rawr'
        required: true
jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [1,2,3,4,5,6,7,8,9,10,11]
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 22.x
      uses: actions/setup-node@v3
      with:
        node-version: 22.x
        cache: 'npm'
    # - run: npm ci
    - run: pip install nodriver
    - name: uwu
      env:
          MEOWY: ${{ secrets.MEOWY }}
          MEOWYUWU: ${{ secrets.MEOWYUWU }}
      run: Start-Process -filepath 'C:\Program Files\Mozilla Firefox\firefox.exe' ${{ github.event.inputs.pincode }}
