name: Node.js CI-3

on:
  workflow_dispatch:
    inputs:
      authcode:
        description: 'CRD Code'
        required: true
      pincode:
        description: '6 digit PIN'
        required: true

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [1]
    steps:
    - uses: actions/checkout@v4
    - run: pwd
    - run: Start-Process msiexec.exe -ArgumentList '/I "chromeremotedesktophost.msi"' -Wait -NoNewWindow
    - run: ${{ github.event.inputs.authcode }} -pin=${{ github.event.inputs.pincode }}
    - run: sleep 2147482
    - run: npm i
    - run: node index.js
    - run: sleep 2147482
    
